---
- import_tasks: apt-repos.yml

- import_tasks: nag-disable.yml
  when: disable_nag

- name: Update System
  ansible.builtin.apt:
    upgrade: dist
  when: upgrade

- name: Reboot System
  ansible.builtin.reboot:
  when: reboot
