---
- name: Disable Enterprise Repo
  ansible.builtin.replace:
    path: "{{ proxmox_nosub_enterprise_repo_path }}"
    regexp: '^deb(\s+.*)?'
    replace: '# deb\1'
  notify: Update

- name: Enable No-Subscription Repo
  ansible.builtin.lineinfile:
    path: "{{ proxmox_nosub_nosub_repo_path }}"
    line: "{{ proxmox_nosub_nosub_repo_line }}"
    create: true
    mode: u=rw,g=r,o=r
  notify: Update
