---
- name: Disable Enterprise Repo
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb(\s+.*)?'
    replace: '# deb\1'
  when: proxmox_nosub_disable_enterprise_repo
  notify: Update

- name: Enable No-Subscription Repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-nosub.list
    line: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
    create: true
    mode: u=rw,g=r,o=r
  when: proxmox_nosub_enable_nosub_repo
  notify: Update

- name: Enable Test Repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-test.list
    line: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pvetest
    create: true
    mode: u=rw,g=r,o=r
  when: proxmox_nosub_enable_test_repo
  notify: Update
