---
- name: Disable Enterprise Repo
  ansible.builtin.replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb(\s+.*)?'
    replace: "# deb"

- name: Enable No-Subscription Repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-nosub.list
    line: deb http://download.proxmox.com/debian/pve {{ ansible_lsb.codename }} pve-no-subscription
    creates:
    mode: u=rw,g=r,o=r

- name: Disable Subscription Prompt >:)
  ansible.builtin.command:
    cmd: |
      echo "DPkg::Post-Invoke { \"dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$'; if [ \$? -eq 1 ]; then { sed -i '/data.status/{s/\!//;s/Active/NoMoreNagging/}' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js; }; fi\"; };" > /etc/apt/apt.conf.d/no-nag-script
      apt --reinstall install proxmox-widget-toolkit &>/dev/null
  when: disable_nag

- name: Update System
  ansible.builtin.apt:
    upgrade: dist
  when: upgrade

- name: Reboot System
  ansible.builtin.reboot:
  when: reboot
