---
- name: Disable Subscription Prompt >:)
  ansible.builtin.lineinfile:
    line: DPkg::Post-Invoke { \"dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$'; if [ \$? -eq 1 ]; then { echo 'Removing subscription nag from UI...'; sed -i '/data.status/{s/\!//;s/Active/NoMoreNagging/}' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js; }; fi\"; };
    path: /etc/apt/apt.conf.d/99no-nag-script
    create: true
  register: __nonag_file__

- name: Reinstall widget toolkit
  ansible.builtin.shell: apt --reinstall install proxmox-widget-toolkit &>/dev/null
  when: __nonag_file__.changed
